# Generated by Django 5.1.3 on 2024-11-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingId', models.IntegerField(verbose_name='buildingId')),
                ('buildingAdres', models.TextField(verbose_name='Adres')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classId', models.IntegerField(verbose_name='classId')),
            ],
        ),
    ]
