# Generated by Django 5.1.2 on 2024-11-11 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountInfo', models.TextField(verbose_name='account info')),
                ('role', models.BooleanField(verbose_name='role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseInfo', models.TextField(verbose_name='coourse info')),
            ],
        ),
        migrations.CreateModel(
            name='CourseExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseExampleInfo', models.TextField(verbose_name='example info')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyInfo', models.TextField(verbose_name='faculty info')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonInfo', models.TextField(verbose_name='lesson info')),
                ('lessonDate', models.DateField(verbose_name='lesson Date')),
                ('lessonTime', models.DateTimeField(verbose_name='lesson time')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNumber', models.IntegerField(verbose_name='room number')),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.TextField(verbose_name='group name')),
            ],
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.RemoveField(
            model_name='building',
            name='buildingId',
        ),
        migrations.AlterField(
            model_name='building',
            name='buildingAdres',
            field=models.TextField(default='blk5', verbose_name='building adres'),
        ),
    ]
