# Generated by Django 5.1.2 on 2024-11-12 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_account_course_courseexample_faculty_lesson_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='inCourseExample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table.courseexample'),
        ),
        migrations.AddField(
            model_name='account',
            name='inFaculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table.faculty'),
        ),
        migrations.AddField(
            model_name='account',
            name='inGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table.studygroup'),
        ),
        migrations.AddField(
            model_name='building',
            name='inFaculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table.faculty'),
        ),
        migrations.AddField(
            model_name='courseexample',
            name='inCourse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table.course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='inRoom',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='table.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='inBuilding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table.building'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='inFaculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table.faculty'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='inLesson',
            field=models.ManyToManyField(null=True, to='table.lesson'),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseInfo',
            field=models.TextField(null=True, verbose_name='coourse info'),
        ),
    ]
